### ISSUE TITLE
More details about usage

### ISSUE THREAD

**Issue by yy9568** [atulkum/rotated_yolo#1]
Hi @atulkum, thank you for your great job, I have met some problem when I implemented a rotated yolo to detect text lines, so I wanna study in your work to find what wrong in my implementation, could you please tell me how to use your code？Does it work for detecting rotated object?

**Comment by atulkum** [comment]
It gave decent result but i was not able to spend much time on it. So yo might need to fine-tune it but the experimental code is implemented. The training code is in https://github.com/atulkum/object_detection/blob/master/rbox/train.py and the model is https://github.com/atulkum/object_detection/blob/master/rbox/rolo.py
And for prediction you can use https://github.com/atulkum/object_detection/blob/master/rbox/predict.py
This is some visualization code https://github.com/atulkum/object_detection/blob/master/initial.ipynb

**Comment by yy9568** [comment]
@atulkum Thank you for your reply but do you still have any visualized image about your result？

**Comment by atulkum** [comment]
No. I did this work long time back.

**Comment by yy9568** [comment]
Thank @atulkum, I had implemented rotated box yolo, based on [this repo](https://github.com/eriklindernoren/PyTorch-YOLOv3).  Thank you for your great job, it gave me inspiration, but [box_iou_rotated](https://github.com/atulkum/object_detection/blob/5401001820a1fea9de89d451556d4c4da19b9dea/rbox/iou_utils.py#L9) confuses me, I think that it has a better way to compute rotated boxes' IoUs rather than cv2.rotatedRectangleIntersection, for example, clipper or pyclipper are helpful and efficient. But there is a situation that two rotated anchors will get the same IoU with specific ground truth, for example, a ground truth with angle is 0 degree, but two anchors which angles are 60 degree and 120 degree, in some case, they will get the same iou with gt. I think it needs to solve in your code.

**Comment by atulkum** [comment]
Thanks for the suggestion. I will try it once I come back to it.

**Comment by yy9568** [comment]
You are welcome.



---Original---
